### ISSUE TITLE
一些 webpack loader 的配置

### ISSUE THREAD

**Issue by wlsyne** [wlsyne/Blog#29]
# 一些 webpack loader 的配置

## 前情提要

**loader 的配置**

```javascript
{
  module: {
    rule: [
      {
        test: '/.css$/',
        use: ['style-loader', 'css-loader', 'postcss-loader'],
      },
    ];
  }
}
```

**loader 执行顺序**

匹配到一个文件，loader 会从右边到左边依次执行处理

### importLoaders

我读完了这个 [issue](https://github.com/webpack-contrib/css-loader/issues/228) 的所有讨论终于弄明白了

当你使用 css @import 了其他的 css 文件，那么就需要这个属性，比如说你是如下配置的 loader

```javascript
{
  test: /\.css$/,
  use: [
    MiniCssExtractPlugin.loader,
    {
      loader: 'css-loader',
      options: {
        importLoaders: 1,
      },
    },
    'postcss-loader',
  ],
};
```

```css
/* A.css */
@import './test.css';

.title {
  text-align: center;
}

/* test.css */
::placeholder {
  color: gray;
}
```

此时的处理链路是 postcss-loader ----> css-loader,因为 webpack 只能在同一时间编译一个文件,处理到 A.css 时首先经过了 postcss-loader 的处理，然后交给 css-loader 处理，此时 css-loader 发现@import 语法，然后 css-loader 去处理 test.css，如果此时你需要再让之前的 loader 处理这个 test.css 那么你就需要加上 `importLoaders` 这个属性,这个属性接受一个 number，表示需要再经过之前的几个 loader 的处理，比如说此时我们只需要之前的 postcss-loader 的处理那么`importLoaders=1`即可

**不加 importLoaders 的处理结果**

```css
::placeholder {
  color: gray;
}

.title {
  text-align: center;
}
```

**加上 importLoaders 的处理结果**

```css
::-moz-placeholder {
  color: gray;
}
:-ms-input-placeholder {
  color: gray;
}
::placeholder {
  color: gray;
}

.title {
  text-align: center;
}
```

如果你使用了 less-loader 或者 sass-loader 那么就可以不使用这个 option 了，因为@import 语法是交给 less-loader 或者 sass-loader 处理的，然后生成 css 文件，再交给 postcss-loader 处理，因此就不需要 css-loader 再处理@import 语法啦
可以看看这个 [issue](https://github.com/webpack-contrib/css-loader/issues/228#issuecomment-312885975)

### modules

用以配置 css-modules

**mode**
默认值 local，可选值 local、global、pure

- local:需要显示声明:global
- global:需要显示声明:local

**localIdentName**

配置生成的 ident 标识，查看[配置项](https://github.com/webpack/loader-utils#interpolatename)
`[local]__[hash:base64:5]`生成的 ident`app_title__3aKz1`

**getLocalIdent**

自定义生成 ident 标识的函数

## react-svg-loader

react-svg-loader 可以将 svg 转成 react 组件,但是必须要配合 babel 进行使用，svg --> svg component --> babel-preset-react

```javascript
import Image1 from 'react-svg-loader!./image1.svg';
<Image1 width={50} height={50} />;
```
